<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toutes nos activités</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="activite.css">
</head>
<body>
    <!-- HEADER -->
    <header class="fixed-top">
        <!-- LIENS DE CONNEXION -->
        <div class="text-right" id="auth">
            <a href="#">Inscription</a> <span id="sep-auth">|</span> <a href="#" class="auth-decal">Connexion</a>
        </div>
                <!-- MENU -->
                <nav class="navbar navbar-expand-lg container navbar-dark">
                    <a class="navbar-brand" href="#">
                        <img src="./assets/logo/logoValhalla.png" alt="Logo Viking Park" width="250" height="auto">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-carousel-item active">
                                <a class="nav-link" href="index.phtml">Accueil</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="attraction.phtml">Attractions</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="activite.phtml">Evènements</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="reservation.phtml">Pré-réserver</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="contact.phtml">Contact</a>
                            </li>
                        </ul>
                    </div>
                </nav>      
    </header>

    <!-- LES ACTIVITES -->
    <main class="container">
        <section class="activite">
            <h2>Nos animations</h2>
            <div class="row">            
                    <div class="col-md-4">
                        <h3>Nom animation</h3>
                        <a href="#"><img src="./assets/images/attractions_example.jpg" alt="attraction exemple" width="100%" height="auto"></a>
                        <div class="favori"><a href="#"><img src="./assets/icone/love.svg" alt="" width="50px" width="auto"></a></div>                    
                        <p>Description de l'animation avec un bref paragraphe</p>
                    </div>
            </div>
        </section>

        <section class="activite">
            <h2>Nos spectacles</h2>
            <div class="row">            
                    <div class="col-md-4">
                        <h3>Nom spectacle</h3>
                        <a href="#"><img src="./assets/images/attractions_example.jpg" alt="attraction exemple" width="100%" height="auto"></a>
                        <div class="favori"><a href="#"><img src="./assets/icone/love.svg" alt="" width="50px" width="auto"></a></div>                    
                        <p>Description du spectacle avec un bref paragraphe</p>
                    </div>
            </div>
        </section>
    </main>

    <!-- FOOTER -->
    <footer>
        <div class="container">
            <ul class="nav justify-content-center">
                <li class="nav-item"><a href="#" class="nav-link">Mentions légales</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Cookies</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Protection des données</a></li>
            </ul>
            <div>© 2020 - Viking Park. Tous droits réservés</div>
        </div>
    </footer>
</body>
</html>