<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toutes nos activités</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="activite.css">
</head>
<body>
    <!-- HEADER -->
    <?php include 'include/header.phtml' ?>

    <!-- LES ACTIVITES -->
    <main class="container">
        <section class="activite">
            <h2>Nos animations</h2>
            <div class="row">  
                <?php foreach($resultAllAnimation as $animation) { ?>              
                    <div class="col-md-4">
                        <h3><?php echo $animation['name_activity']; ?></h3>
                        <a href="content.php?activity=<?php echo $animation['Id_activity']; ?>"><img src="./assets/images/<?php echo $animation['image_banner']; ?>" alt="<?php echo $animation['name_activity']; ?>" width="100%" height="200px"></a>
                        <div class="favori"><a href="#"><img src="./assets/icone/love.svg" alt="" width="50px" width="auto"></a></div>                    
                        <p><?php echo $animation['description_activity']; ?></p>
                    </div>
                <?php } ?>
            </div>
        </section>

        <section class="activite">
            <h2>Nos spectacles</h2>
            <div class="row"> 
                <?php foreach($resultAllSpectacle as $spectacle) { ?>             
                    <div class="col-md-4">
                        <h3><?php echo $spectacle['name_activity']; ?></h3>
                        <a href="content.php?activity=<?php echo $spectacle['Id_activity']; ?>"><img src="./assets/images/<?php echo $spectacle['image_banner']; ?>" alt="<?php echo $spectacle['name_activity']; ?>" width="100%" height="200px"></a>
                        <div class="favori"><a href="#"><img src="./assets/icone/love.svg" alt="" width="50px" width="auto"></a></div>                    
                        <p><?php echo $spectacle['description_activity']; ?></p>
                    </div>
                <?php } ?>
            </div>
        </section>
    </main>

    <!-- FOOTER -->
    <?php include 'include/footer.phtml' ?>
    
</body>
</html>