<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toutes nos attractions</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="attraction.css">
</head>
<body>
    <!-- HEADER -->
    <?php include 'include/header.phtml' ?>

    <!-- LISTE DES ATTRACTIONS -->
    <main class="container" id="attraction_list">
        <h2>Toutes nos attractions</h2>        
        <div class="row" >   
            <?php foreach($resultAllAttraction as $attraction) { ?>         
                <div class="col-md-4">
                    <h3><?php echo $attraction['name_activity']; ?></h3>
                    <a href="content.php?activity=<?php echo $attraction['Id_activity']; ?>"><img src="./assets/images/<?php echo $attraction['image_banner']; ?>" alt="<?php echo $attraction['name_activity']; ?>" width="100%" height="200px"></a>
                    <div class="favori"><a href="#"><img src="./assets/icone/love.svg" alt="" width="50px" width="auto"></a></div>                    
                    <p><?php echo $attraction['description_activity']; ?></p>
                </div>
            <?php } ?>
        </div>
        
    </main>

    <!-- FOOTER -->
    <?php include 'include/footer.phtml' ?>
    
</body>
</html>