<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contactez-nous !</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="contact.css">
</head>

<body>
    <!-- HEADER -->
    <?php include 'include/header.phtml' ?>

    <!-- FORMULAIRE -->
    <div class="container" id="contact">
        <h2>Contactez-nous !</h2>
        <p>Vous avez des questions ? Vous souhaitez en savoir plus sur le park ? <br>
            N'hésitez pas à nous laissez une message, nous vous répondrons dans les plus brefs délais.</p>
        <form action="contact/sendMail.php" method="post">
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <input type="text" name="nom" placeholder="NOM *">
                    </div>
                    <div>
                        <input type="text" name="email" placeholder="EMAIL *">
                    </div>
                </div>

                <div class="col-md-6">
                    <div>
                        <input type="text" name="sujet" placeholder="SUJET *">
                    </div>
                    <textarea placeholder="SAISISSEZ ICI VOTRE MESSAGE *" name="message" rows="5"></textarea>
                </div>
            </div>
            <div class="offset-6" id="buttonSubmit">
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </div>
            <!-- Gestion des erreurs -->
            <p>
                <?php
                if (isset($_GET['message'])) {
                    if ($_GET['message'] == 'error') {
                        echo 'Veuillez remplir tous les champs';
                    }
                }
                ?>
            </p>
        </form>
    </div>

    <!-- RESEAUX SOCIAUX & NEWSLETTER -->
    <section id="social">
        <div class="container">
            <div class="row">
                <div class="col-md-6" id="socialNetwork">
                    <h2>Réseaux Sociaux</h2>
                    <p>Rejoingez-nous sur les réseaux sociaux et partagez vos attractions préférées avec vos ami(e)s.</p>
                    <div>
                        <div id="socialIcone">
                            <a href="https://www.facebook.com/"><img src="./assets/icone/iconeFacebook.svg" alt="Icone Facebook" width="50" height="50"></a>
                            <a href="https://twitter.com"><img src="./assets/icone/iconeTwitter.svg" alt="Icone Twitter" width="50" height="50"></a>
                            <a href="https://www.instagram.com"><img src="./assets/icone/iconeInstagram.svg" alt="Icone Instagram" width="50" height="50"></a>
                            <a href="https://www.youtube.com"><img src="./assets/icone/iconeYoutube.svg" alt="Icone Youtube" width="50" height="50"></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6" id="newsletter">
                    <h2>Newsletter</h2>
                    <p>Restez au courant des actualités du parc et profitez de promotions exclusives</p>
                    <form action="contact/newsletter.php" method="post" class="form-group row">
                        <label for="newsletter" class="col-3">Votre email : </label>
                        <input type="text" name="newsletter" placeholder="Entrez votre email..." class="form-control col-6" id="inputNewsletter">
                        <button type="submit" class="btn btn-primary col-3" id="btnNewsletter">S'abonner</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <!-- SNACKBAR -->
    <div id="snackbar">
        <?php
        if (isset($_GET['message']) == 'valide') {
            echo 'Votre message a bien été envoyé';
        }
        ?>
    </div>

    <!-- Script pour lancer le toast -->
    <script>
        function myFunction() {
            // Get the snackbar DIV
            var x = document.getElementById("snackbar");

            // Add the "show" class to DIV
            x.className = "show";

            // After 3 seconds, remove the show class from DIV
            setTimeout(function() {
                x.className = x.className.replace("show", "");
            }, 3000);
        }

        <?php if (isset($_GET['message']) and $_GET['message'] == 'valide') { ?>
            //Lance le snackbar au chargement de la page
            window.onload = myFunction;
        <?php } ?>
    </script>

    <!-- FOOTER -->
    <?php include 'include/footer.phtml' ?>

</body>

</html>