<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="content.css">
    <script src="content.js" defer></script>
</head>
<body>
    <!-- HEADER -->
    <?php include 'include/header.phtml' ?>

    <div style="background-image: url(./assets/images/<?php echo $activityContent['image_banner']; ?>)" id="contentBanner">
        <h2><?php echo $activityContent['name_activity']; ?></h2>
    </div>

    <!-- CONTENU -->
    <main class="container">
    <?php if (isset($_SESSION['id'])) { ?>
        <form action="content/notation.php?content=<?php echo $activityContent['Id_activity'] ?>" method="post">
            <h3>Notations de l'activité</h3>

            <span class="fa fa-star checked" id="star1"></span>
            <span class="fa fa-star checked" id="star2"></span>
            <span class="fa fa-star checked" id="star3"></span>
            <span class="fa fa-star" id="star4"></span>
            <span class="fa fa-star" id="star5"></span>

            <span id="resultRating">3/5</span>
            <input type="hidden" name="rating" id="rating" value=3>

            <div><button type="submit" class="btn btn-primary">Envoyer</button></div>
            <div><?php 
                if(isset($_GET['notation']) == "error") {
                    echo "Vous avez déjà noté cette activité";
                } else if (isset($_GET['notation']) == "success") {
                    echo "Votre note a été pris en compte";
                }
            ?></div>

        </form>
    <?php } ?>

        <div id="descriptionContent" class="col-md-8 offset-md-2">
            <p><?php echo $activityContent['description_activity']; ?></p>
        </div>

        <div id="buttonList">
            <?php if ($activityContent['type_activity'] == "attraction") { ?>
                <a href="attraction.php" type="button" class="btn btn-primary">Voir toutes les attractions</a>
            <?php } else { ?>
                <a href="activite.php" type="button" class="btn btn-primary">Voir toutes les évènements</a>
            <?php } ?>
        </div>
        

        <!-- CAROUSEL -->
        <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
            <!-- Indicators -->
            <ul class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ul>

            <!-- Image du carousel -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="./assets/images/<?php echo $activityContent['imageA']; ?>" alt="" width="100%" height="auto">
                </div>
                <div class="carousel-item">
                    <img src="./assets/images/<?php echo $activityContent['imageB']; ?>" alt="" width="100%" height="auto">
                </div>
                <div class="carousel-item">
                    <img src="./assets/images/<?php echo $activityContent['imageC']; ?>" alt="" width="100%" height="auto">
                </div>
                <div class="carousel-item">
                    <img src="./assets/images/<?php echo $activityContent['imageD']; ?>" alt="" width="100%" height="auto">
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

        <!-- SECTION COMMENTAIRE -->
        <section>
            <!-- Formulaire pour commenter l'activité -->
            <form action="content/commentaire.php?activity=<?php echo $activityContent['Id_activity']; ?>" method="post">
                <div>
                    <label for="">Pseudo :
                        <input type="text" name="pseudo" value="<?php if (isset($_SESSION['pseudo'])) {
                            echo $_SESSION['pseudo'];
                        } ?>">
                    </label>
                </div>                
                
                <div>
                    <label for="">Commentaires :</label> 
                        <textarea name="commentaire" id="" cols="30" rows="10"></textarea>
                    
                </div>                               

                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>

            <!-- Affichage des commentaires -->
            <div>
                <table class="table">
                    <tbody>
                        <?php foreach($allCommentaries as $comment) { ?>
                        <tr>
                            <td class="pseudoStrong"><?php echo $comment['pseudo']; ?></td>
                            <td><?php echo $comment['commentaire']; ?><br>
                            <span class="post_date"><?php echo $comment['date_post']; ?></span></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </section>
    </main>

    <!-- FOOTER -->
    <?php include 'include/footer.phtml' ?>
</body>
</html>