<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contactez-nous !</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="contact.css">
</head>
<body>
    <!-- HEADER -->
    <header class="fixed-top">
        <!-- LIENS DE CONNEXION -->
        <div class="text-right" id="auth">
            <a href="#">Inscription</a> <span id="sep-auth">|</span> <a href="#" class="auth-decal">Connexion</a>
        </div>
                <!-- MENU -->
                <nav class="navbar navbar-expand-lg container navbar-dark">
                    <a class="navbar-brand" href="#">
                        <img src="./assets/logo/logoValhalla.png" alt="Logo Viking Park" width="250" height="auto">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-carousel-item active">
                                <a class="nav-link" href="index.phtml">Accueil</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="attraction.phtml">Attractions</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="activite.phtml">Evènements</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="#">Pré-réserver</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="contact.phtml">Contact</a>
                            </li>
                        </ul>
                    </div>
                </nav>      
    </header>

    <!-- FORMULAIRE -->
    <div class="container" id="contact">
        <h2>Contactez-nous !</h2>
        <p>Vous avez des questions ? Vous souhaitez en savoir plus sur le park ? <br>
        N'hésitez pas à nous laissez une message, nous vous répondrons dans les plus brefs délais.</p>
        <form action="">
            <div class="row">
                <div class="col-md-6">
                    <div>
                        <input type="text" placeholder="NOM *">
                    </div>
                    <div>
                        <input type="text" placeholder="PRENOM *">
                    </div>
                    <div>
                        <input type="text" placeholder="EMAIL *">
                    </div>
                </div>
                
                <div class="col-md-6">
                <textarea placeholder="SAISISSEZ ICI VOTRE MESSAGE *"></textarea>
                </div>
            </div>            

            <button type="submit" class="btn btn-primary">Envoyer</button>
        </form>
    </div>

    <!-- RESEAUX SOCIAUX & NEWSLETTER -->
    <section id="social">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2>Réseaux Sociaux</h2>
                    <p>Rejoingez-nous sur les réseaux sociaux et partagez vos attractions préférées avec vos ami(e)s.</p>
                    <div>
                        <div id="socialIcone">
                            <a href="https://www.facebook.com/"><img src="./assets/icone/iconeFacebook.svg" alt="Icone Facebook" width="50" height="50"></a>
                            <a href="https://twitter.com"><img src="./assets/icone/iconeTwitter.svg" alt="Icone Twitter" width="50" height="50"></a>
                            <a href="https://www.instagram.com"><img src="./assets/icone/iconeInstagram.svg" alt="Icone Instagram" width="50" height="50"></a>
                            <a href="https://www.youtube.com"><img src="./assets/icone/iconeYoutube.svg" alt="Icone Youtube" width="50" height="50"></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <h2>Newsletter</h2>
                    <p>Restez au courant des actualités du parc et profitez de promotions exclusives</p>
                    <form action="" class="form-group row">
                        <label for="newsletter" class="col-3">Votre email : </label>
                        <input type="text" name="newsletter" placeholder="Entrez votre email..." class="form-control col-6" id="inputNewsletter">
                        <button type="submit" class="btn btn-primary col-3" id="btnNewsletter">S'abonner</button>
                    </form>
                </div>
            </div>            
        </div>
        </section>

    <!-- FOOTER -->
    <footer>
        <div class="container">
            <ul class="nav justify-content-center">
                <li class="nav-item"><a href="#" class="nav-link">Mentions légales</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Cookies</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Protection des données</a></li>
            </ul>
            <div>© 2020 - Viking Park. Tous droits réservés</div>
        </div>
    </footer>
</body>
</html>