<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - admin</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="dashboard.css">
    <script src="dashboard.js" defer></script>
</head>

<body>
    <!-- HEADER -->
    <?php include 'include/header.phtml' ?>

    <div id="dashboard">
        <div class="container">
            <h2>Dashboard</h2>

            <!-- BOUTON POUR GERER LES AUTORISATIONS DES UTILISATEURS -->
            <?php if ($_SESSION['type'] == 1) { ?>
                <div>
                    <h3>Liste des utilisateurs du site</h3>
                    <div id="list-user">
                        <a href="list-users.php" class="btn btn-primary">Voir la liste</a>
                    </div>
                </div>
            <?php } ?>

            <!-- FORMULAIRE POUR AJOUTER UN CONTENU -->
            <div>
                <h3>Ajouter un contenu</h3>
                <form action="dashboard/addContent.php" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="titre">Titre de l'activité :
                            <input type="text" name="titre" placeholder="Ajouter un titre" class="form-control"></label>
                    </div>
                    <div class="form-group">
                        <label for="description">Description de l'activité :
                            <input type="text" name="description" placeholder="Ajoutez une description" class="form-control"></label>
                    </div>
                    <div class="form-group">
                        <label for="type">Type de l'activité : <a id="addNewType">+ Ajouter un type</a>
                            <select class="form-control" name="typeSelect">
                                <!-- En fonction des type qu'il y a en database -->
                                <option value="attraction">Attraction</option>
                                <option value="spectacle">Spectacle</option>
                                <option value="animation">Animation</option>
                            </select>
                            <input type="text" name="type" placeholder="Ajoutez un type" class="form-control" id="addType"></label>
                    </div>
                    <div class="form-group">
                        <label for="imageBanner">Image bannière :
                            <input type="File" name="imageBanner">
                        </label>
                        <label for="imageBanner">Image présentation 1 :
                            <input type="File" name="imageA">
                        </label>
                        <label for="imageBanner">Image présentation 2 :
                            <input type="File" name="imageB">
                        </label>
                        <label for="imageBanner">Image présentation 3 :
                            <input type="File" name="imageC">
                        </label>
                        <label for="imageBanner">Image présentation 4 :
                            <input type="File" name="imageD">
                        </label>
                    </div>

                    <button type="submit" class="btn btn-primary mx-auto">Ajouter l'activité</button>
                </form>
                <p><?php
                    if (isset($_GET['ajout-contenu']) and $_GET['ajout-contenu'] == 'error') {
                        echo 'Veuillez remplir tous les champs';
                    }
                    if (isset($_GET['ajout-titre']) and $_GET['ajout-titre'] == 'error') {
                        echo 'Cette activité existe déjà';
                    }
                    ?></p>
            </div>

            <!-- LISTE DES CONTENUS -->
            <div>
                <h3>Liste des contenus</h3>

                <!-- Check si il y a un get update pour afficher le formulaire de modification -->
                <?php
                if (isset($_GET['update']) != '') {
                    //Charger les data du contenu à modifier
                    $updateContent = $database->prepare("SELECT name_activity, description_activity, type_activity FROM activity WHERE Id_activity = ?");
                    $updateContent->execute(array($_GET['update']));
                    $dateUpdateContent = $updateContent->fetch();
                ?>
                    <form action="dashboard/updateContent.php?update=<?php echo $_GET['update']; ?>" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="titre">Titre de l'activité :
                                <input type="text" name="titre" value="<?php echo $dateUpdateContent['name_activity'] ?>" class="form-control"></label>
                        </div>
                        <div class="form-group">
                            <label for="description">Description de l'activité :
                                <input type="text" name="description" value="<?php echo $dateUpdateContent['description_activity'] ?>" class="form-control"></label>
                        </div>
                        <div class="form-group">

                            <label for="type">Type de l'activité :
                                <input type="text" name="type" value="<?php echo $dateUpdateContent['type_activity'] ?>" class="form-control"></label>
                        </div>

                        <div class="form-group">
                            <label for="imageBanner">Image bannière :
                                <input type="File" name="imageBanner">
                            </label>
                            <label for="imageBanner">Image présentation 1 :
                                <input type="File" name="imageA">
                            </label>
                            <label for="imageBanner">Image présentation 2 :
                                <input type="File" name="imageB">
                            </label>
                            <label for="imageBanner">Image présentation 3 :
                                <input type="File" name="imageC">
                            </label>
                            <label for="imageBanner">Image présentation 4 :
                                <input type="File" name="imageD">
                            </label>
                        </div>

                        <button type="submit" class="btn btn-primary mx-auto">Modifier l'activité</button>
                        <p><?php
                            if (isset($_GET['update-content']) and $_GET['update-content'] == 'error') {
                                echo 'Veuillez remplir tous les champs';
                            }
                            ?></p>
                    </form>
                <?php
                }
                ?>

                <table class="table">
                    <?php foreach ($activities as $activity) { ?>
                        <thead class="thead-dark">
                            <tr>
                                <th>Nom de l'activité</th>
                                <th>Description de l'activité</th>
                                <th>Type d'activité</th>
                                <th>Modifier</th>
                                <th>Supprimer</th>                                
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?php echo $activity['name_activity']; ?></td>
                                <td><?php echo $activity['description_activity']; ?></td>
                                <td><?php echo $activity['type_activity']; ?></td>
                                <td><a href="dashboard.php?update=<?php echo $activity['Id_activity']; ?>" class="btn btn-warning">Modifier</a></td>
                                <td><a href="dashboard/deleteActivity.php?activity=<?php echo $activity['Id_activity']; ?>" class="btn btn-danger">Supprimer</a></td>
                            </tr>
                        </tbody>
                        <thead class="thead-light">
                            <tr>
                                <th>Image bannière</th>
                                <th>Image A</th>
                                <th>Image B</th>
                                <th>Image C</th>
                                <th>Image D</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><img src="./assets/images/<?php echo $activity['image_banner']; ?>" alt="" width="150px" height="auto"></td>
                                <td><img src="./assets/images/<?php echo $activity['imageA']; ?>" alt="" width="150px" height="auto"></td>
                                <td><img src="./assets/images/<?php echo $activity['imageB']; ?>" alt="" width="150px" height="auto"></td>
                                <td><img src="./assets/images/<?php echo $activity['imageC']; ?>" alt="" width="150px" height="auto"></td>
                                <td><img src="./assets/images/<?php echo $activity['imageD']; ?>" alt="" width="150px" height="auto"></td>
                            </tr>
                        </tbody>
                    <?php } ?>
                </table>

            </div>

            <!-- RECAPITULATIF DES NOTES -->
            <div>
                <h3>Récapitulatif des notes</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nom de l'activité</th>
                            <th>Moyenne des notes</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($likeActivities as $likeActivity) { ?>
                            <tr>
                                <td><?php echo $likeActivity['name_activity']; ?></td>
                                <td><?php echo (int)$likeActivity['total_note'] . " / 5"; ?></td>
                                <td><a href="recap-note.php?id=<?php echo $likeActivity['name_activity']; ?>" class="btn btn-primary">Voir le récap de l'activité</a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- SNACKBAR -->
    <div id="snackbar">
        <?php
        if (isset($_GET['ajout-contenu']) and $_GET['ajout-contenu'] == 'success') {
            echo 'Votre activité a bien été ajoutée';
        }
        if (isset($_GET['update']) and $_GET['update'] == 'success') {
            echo 'Votre activité a bien été modifiée';
        }
        ?>
    </div>

    <!-- Script pour lancer le toast -->
    <script>
        function myFunction() {
            // Get the snackbar DIV
            var x = document.getElementById("snackbar");

            // Add the "show" class to DIV
            x.className = "show";

            // After 3 seconds, remove the show class from DIV
            setTimeout(function() {
                x.className = x.className.replace("show", "");
            }, 3000);
        }

        <?php if (isset($_GET['ajout-contenu']) and $_GET['ajout-contenu'] == 'success' or isset($_GET['update']) and $_GET['update'] == 'success') { ?>
            //Lance le snackbar au chargement de la page
            window.onload = myFunction;
        <?php } ?>
    </script>
</body>

</html>