<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - admin</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="dashboard.css">
    <script src="dashboard.js" defer></script>
</head>
<body>
    <!-- HEADER -->
    <?php include 'include/header.phtml' ?>

    <div id="dashboard">
        <div class="container">
            <h2>Dashboard</h2>

            <!-- FORMULAIRE POUR AJOUTER UN CONTENU -->
            <div>
                <h3>Ajouter un contenu</h3>
                <form action="dashboard/addContent.php" method="post">
                    <div class="form-group">
                        <label for="titre">Titre de l'activité : 
                        <input type="text" name="titre" placeholder="Ajouter un titre" class="form-control"></label>
                    </div>
                    <div class="form-group">
                        <label for="description">Description de l'activité : 
                        <input type="text" name="description" placeholder="Ajoutez une description" class="form-control"></label>
                    </div>
                    <div class="form-group">
                        
                        <label for="type">Type de l'activité : <a id="addNewType">+ Ajouter un type</a>
                        <select class="form-control" name="typeSelect">
                            <!-- En fonction des type qu'il y a en database -->
                            <option value="attraction">Attraction</option>
                            <option value="spectacle">Spectacle</option>
                            <option value="animation">Animation</option>
                        </select>
                        <input type="text" name="type" placeholder="Ajoutez un type" class="form-control" id="addType"></label>
                    </div>

                    <button type="submit" class="btn btn-primary mx-auto">Ajouter l'activité</button>
                </form>
                <p><?php 
                    if (isset($_GET['ajout-contenu']) AND $_GET['ajout-contenu'] == 'error') {
                        echo 'Probleme lors de l ajout du contenu';
                    } else if (isset($_GET['ajout-contenu']) AND $_GET['ajout-contenu'] == 'success') {
                        echo 'Ajout pris en compte';
                    }
                ?></p>
            </div>

            <!-- LISTE DES CONTENUS -->
            <div>
                <h3>Liste des contenus</h3>

                <!-- Check si il y a un get update pour afficher le formulaire de modification -->
                <?php 
                    if (isset($_GET['update']) != '') {
                        //Charger les data du contenu à modifier
                        $updateContent = $database ->prepare("SELECT name_activity, description_activity, type_activity FROM activity WHERE Id_activity = ?");
                        $updateContent->execute(array($_GET['update']));
                        $dateUpdateContent = $updateContent->fetch();
                ?>
                    <form action="dashboard/updateContent.php?update=<?php echo $_GET['update']; ?>" method="post">
                        <div class="form-group">
                            <label for="titre">Titre de l'activité : 
                            <input type="text" name="titre" value="<?php echo $dateUpdateContent['name_activity'] ?>" class="form-control"></label>
                        </div>
                        <div class="form-group">
                            <label for="description">Description de l'activité : 
                            <input type="text" name="description" value="<?php echo $dateUpdateContent['description_activity'] ?>" class="form-control"></label>
                        </div>
                        <div class="form-group">
                            
                            <label for="type">Type de l'activité :
                            <input type="text" name="type" value="<?php echo $dateUpdateContent['type_activity'] ?>" class="form-control"></label>
                        </div>

                        <button type="submit" class="btn btn-primary mx-auto">Modifier l'activité</button>
                    </form>
                <?php 
                    }
                ?>
                
                <?php foreach($activities as $activity) { ?>
                    <div class="row">
                        <div class="col-9">
                            <p><?php echo $activity['name_activity']; ?></p>
                            <p><?php echo $activity['description_activity']; ?></p>
                        </div>
                        <div class="col-3">
                            <a href="dashboard.php?update=<?php echo $activity['Id_activity']; ?>" class="btn btn-warning">Modifier</a>
                            <a href="dashboard/deleteActivity.php?activity=<?php echo $activity['Id_activity']; ?>" class="btn btn-danger">Supprimer</a>
                        </div>
                    </div>
                <?php } ?>

            </div>

            <!-- RECAPITULATIF DES NOTES -->            
            <div>
                <h3>Récapitulatif des notes</h3>

                <?php foreach($likeActivities as $likeActivity) { ?>
                <div>
                    <p><?php echo $likeActivity['name_activity']; ?></p>
                    <p><?php echo $likeActivity['total_note']; ?></p>
                </div>
                <?php } ?>
            </div>                
        </div>
    </div>
</body>
</html>