<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil - Valhalla Park</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- HEADER -->
    <header class="fixed-top">
        <!-- LIENS DE CONNEXION -->
        <div class="text-right" id="auth">
            <a href="#">Inscription</a> <span id="sep-auth">|</span> <a href="#" class="auth-decal">Connexion</a>
        </div>
                <!-- MENU -->
                <nav class="navbar navbar-expand-lg container navbar-dark">
                    <a class="navbar-brand" href="#">
                        <img src="./assets/logo/logoValhalla.png" alt="Logo Viking Park" width="250" height="auto">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-carousel-item active">
                                <a class="nav-link" href="#">Accueil</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="#">Attractions</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="#">Evènements</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="#">Pré-réserver</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="#">Contact</a>
                            </li>
                        </ul>
                    </div>
                </nav>      
    </header>

    <main>
        <!-- BANNIERE -->
        <section id="banniere">
            <div class="container">
                <div class="col-md-6">
                    <h1>Affronte tes peurs avec les dieux nordiques et deviens un vrai <span class="viking">viking</span></h1>
                    <p id="banniere-firstChild">Date d'ouverture : septembre 2021</p>
                    <p id="banniere-lastChild">Venez profiter de votre nouveau parc d'attraction en premier en pré-réservant votre ticket !</p>
                    <button type="button" class="btn btn-primary">Réserver maintenant</button>
                </div>                
            </div>            
        </section>

        <!-- SECTION ATTRACTIONS -->
        <section class="attraction">
            <div class="container">
                <h2>Nos attractions</h2>
                <h3>Faites les pleins de sensations</h3>

                <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">

                <!-- Indicators -->
                <ul class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ul>

                <!-- The slideshow -->
                <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="./assets/images/warViking.jpg" alt="Los Angeles" width="100%" height="auto">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Titre de l'attraction</h5>
                        <p>Phrase d'accroche pour l'attraction</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="./assets/images/bateauViking.jpg" alt="Los Angeles" width="100%" height="auto">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Titre de l'attraction</h5>
                        <p>Phrase d'accroche pour l'attraction</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="./assets/images/warViking.jpg" alt="Los Angeles" width="100%" height="auto">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Titre de l'attraction</h5>
                        <p>Phrase d'accroche pour l'attraction</p>
                    </div>
                </div>
                </div>

                <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#myCarousel" data-slide="next">
                <span class="carousel-control-next-icon"></span>
                </a>
                </div>

                <div class="plusAttraction">
                    <a type="button" class="btn btn-primary" href="#" >Toutes nos attractions</a>
                </div>                
            </div>
        </section>

        <!-- SECTION ACTIVITES -->
        <section class="attraction">
            <div class="container">
                <h2>Nos activités</h2>
                <h3>Entrez dans la peau d'un viking</h3>

                <div id="myCarouselActivite" class="carousel slide carousel-fade" data-ride="carousel">

                <!-- Indicators -->
                <ul class="carousel-indicators">
                    <li data-target="#myCarouselActivite" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarouselActivite" data-slide-to="1"></li>
                    <li data-target="#myCarouselActivite" data-slide-to="2"></li>
                </ul>

                <!-- The slideshow -->
                <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="./assets/images/warViking.jpg" alt="Los Angeles" width="100%" height="auto">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Titre de l'activité</h5>
                        <p>Phrase d'accroche pour l'activité</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="./assets/images/bateauViking.jpg" alt="Los Angeles" width="100%" height="auto">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Titre de l'activité</h5>
                        <p>Phrase d'accroche pour l'activité</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="./assets/images/warViking.jpg" alt="Los Angeles" width="100%" height="auto">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Titre de l'activité</h5>
                        <p>Phrase d'accroche pour l'activité</p>
                    </div>
                </div>
                </div>

                <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#myCarouselActivite" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#myCarouselActivite" data-slide="next">
                <span class="carousel-control-next-icon"></span>
                </a>
                </div>

                <div class="plusAttraction">
                    <a type="button" class="btn btn-primary" href="#" >Toutes nos activités</a>
                </div>                
            </div>
        </section>

        <!-- RESEAUX SOCIAUX & NEWSLETTER -->
        <section id="social">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2>Réseaux Sociaux</h2>
                    <p>Rejoingez-nous sur les réseaux sociaux et partagez vos attractions préférées avec vos ami(e)s.</p>
                    <div>
                        <div id="socialIcone">
                            <a href="https://www.facebook.com/"><img src="./assets/icone/iconeFacebook.svg" alt="Icone Facebook" width="50" height="50"></a>
                            <a href="https://twitter.com"><img src="./assets/icone/iconeTwitter.svg" alt="Icone Twitter" width="50" height="50"></a>
                            <a href="https://www.instagram.com"><img src="./assets/icone/iconeInstagram.svg" alt="Icone Instagram" width="50" height="50"></a>
                            <a href="https://www.youtube.com"><img src="./assets/icone/iconeYoutube.svg" alt="Icone Youtube" width="50" height="50"></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <h2>Newsletter</h2>
                    <p>Restez au courant des actualités du parc et profitez de promotions exclusives</p>
                    <form action="" class="form-group row">
                        <label for="newsletter" class="col-3">Votre email : </label>
                        <input type="text" name="newsletter" placeholder="Entrez votre email..." class="form-control col-6" id="inputNewsletter">
                        <button type="submit" class="btn btn-primary col-3" id="btnNewsletter">S'abonner</button>
                    </form>
                </div>
            </div>            
        </div>
        </section>
    </main>

    <!-- FOOTER -->
    <footer>
        <div class="container">
            <ul class="nav justify-content-center">
                <li class="nav-item"><a href="#" class="nav-link">Mentions légales</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Cookies</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Protection des données</a></li>
            </ul>
            <div>© 2020 - Viking Park. Tous droits réservés</div>
        </div>
    </footer>



</body>
</html>