<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="./style.css">
    <link rel="stylesheet" href="./inscription.css">
</head>
<body>
    <!-- HEADER -->
    <?php include './include/header.phtml' ?>

    <div id="inscription">
        <div class="container">
            <h2>Inscription</h2>
            
            <!-- Formulaire d'inscription -->
            <form action="authentification/inscription_check.php" method="post" class="col-md-6 offset-md-3">
                <div class="form-group">
                    <label for="email">Email : 
                        <input type="text" name="email" placeholder="Entrez votre email *" class="form-control">
                    </label>
                </div>
                <div class="form-group">
                    <label for="pseudo">Pseudo : 
                        <input type="text" name="pseudo" placeholder="Entrez votre pseudo *" class="form-control">
                    </label>
                </div>
                <div class="form-group">
                    <label for="password">Mot de passe : 
                        <input type="password" name="password" placeholder="Entrez votre mot de passe *" class="form-control">
                    </label>                    
                </div> 
                <div class="form-group">
                    <label for="passwordConfirm">Confirmation du mot de passe : 
                        <input type="password" name="passwordConfirm" placeholder="Entrez de nouveau votre mot de passe *" class="form-control">
                    </label>
                </div> 
                <button type="submit" class="btn btn-primary">S'incrire</button>
            </form>

            <p id="error" class="offset-md-3"><?php if (isset($_GET['value']) == 'error' OR isset($_GET['champs']) == 'error') {
                        echo 'Veuillez remplir les champs';
                    } 
                    if (isset($_GET['password']) == 'error') {
                        echo 'Les mots de passe doivent être identiques';
                    } 
                    if (isset($_GET['pseudo']) == 'error') {
                        echo 'Ce pseudo existe déjà';
                    } ?></p>
        </div>
    </div>
</body>
</html>