<footer>
        <div class="container">
            <ul class="nav justify-content-center">
                <li class="nav-item"><a href="#" class="nav-link">Mentions légales</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Cookies</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Protection des données</a></li>
            </ul>
            <div>© 2020 - Viking Park. Tous droits réservés</div>
        </div>
    </footer>