<?php
    session_start();
?>

<header class="fixed-top">
        <!-- LIENS DE CONNEXION -->
        <div class="text-right" id="auth">
            <?php if (isset($_SESSION['pseudo'])) { ?>
                <a href="#"><?php echo $_SESSION['pseudo']; ?></a>
                <span id="deconnexionSeparate"> | </span>
               <a href="authentification/deconnexion.php">Déconnexion</a> 
            <?php } else { ?>
                <a href="inscription.phtml">Inscription</a> <span id="sep-auth">|</span> <a href="connexion.phtml" class="auth-decal">Connexion</a>
            <?php } ?>
        </div>
                <!-- MENU -->
                <nav class="navbar navbar-expand-lg container navbar-dark">
                    <a class="navbar-brand" href="index.phtml">
                        <img src="./assets/logo/logoValhalla.png" alt="Logo Viking Park" width="250" height="auto">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-carousel-item active">
                                <a class="nav-link" href="index.phtml">Accueil</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="attraction.phtml">Attractions</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="activite.phtml">Evènements</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="reservation.phtml">Pré-réserver</a>
                            </li>
                            <li class="nav-carousel-item">
                                <a class="nav-link" href="contact.phtml">Contact</a>
                            </li>
                        </ul>
                    </div>
                </nav>      
    </header>