<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Intégration de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Intégration de mes scripts & styles -->
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h2>Inscription</h2>
    
    <!-- Formulaire d'inscription -->
    <form action="inscription_check.php" method="post">
        <div>
            <label for="email">Email : 
                <input type="text" name="email" placeholder="Entrez votre email">
            </label>
        </div>
        <div>
            <label for="pseudo">Pseudo : 
                <input type="text" name="pseudo" placeholder="Entrez votre pseudo">
            </label>
        </div>
        <div>
            <label for="password">Mot de passe : 
                <input type="password" name="password" placeholder="Entrez votre mot de passe">
            </label>
        </div> 
        <button type="submit">S'incrire</button>
    </form>
</body>
</html>